ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-"{{ env }}".prakritiorganics.store
CATALOGUE_HOST: catalogue-"{{ env }}".prakritiorganics.store
REDIS_HOST: redis-"{{ env }}".prakritiorganics.store
USER_HOST: user-"{{ env }}".prakritiorganics.store
CART_HOST: cart-"{{ env }}".prakritiorganics.store
MYSQL_HOST: mysql-"{{ env }}".prakritiorganics.store
SHIPPING_HOST: shipping-"{{ env }}".prakritiorganics.store
RABBITMQ_HOST: rabbitmq-"{{ env }}".prakritiorganics.store
PAYMENT_HOST: payment-"{{ env }}".prakritiorganics.store